:doctype: book
:compat-mode:
:page-layout!:
:toc: left
:toclevels: 1
:imagesdir: assets
:assetsdir: assets/assets
:compat-mode!:
:linkcss:
:source-highlighter: coderay

= Anypoint™ Connector Certification Process

*version 0.9.2*

[[intro]]
= Certification Process

MuleSoft has expanded the Anypoint™ Connector platform enabling partners, from MuleSoft Partner Program, and third-party development groups, to develop Anypoint™ connectors.

Every connector in the MuleSoft Anypoint™ Platform must go through a mandatory *Certification Process* before final release. This certification process has been conceived to assess the overall quality of all available connectors, ensuring that every connector published in the MuleSoft Connectors library strictly follows industry best practices. As a result of this certification process, we are able to define a high quality threshold for every Anypoint™ connector available in the Mulesoft platform.

All available connectors, either built by our partners or by our internal development team, go through the same certification process, which is carried out by MuleSoft's internal team. Once a connector passes certification, it is branded as a MuleSoft-certified connector and published in the MuleSoft Connectors Library.


The scope of this process mainly depends on the composition of the connector, where a more complex connector will require further steps in the certification process. Our certification approach aims at testing every functional block of the connector prior releasing.


This document first introduces the entire *Connector Lifecycle Model*, which includes four different stages: On-board, Development, Certification and Publishing.

. On-board: Takes into consideration the legal engagement between a third-party development group or partner, and MuleSoft.
. Development: The development stage, considering strictly testing methodologies.
. Certification: The certification process per-se, carried out by a MuleSoft.
. Publishing: Considers the final deployment of the certified connector within MuleSoft Connectors Library.

Within these stages, we only take into consideration the second and third ones: Development and Certification. The first stage is out of the scope of this document, while the last one hardly requires interaction from the developer's side and therefore it will be omitted.



[[connector-lifecycle-model]]
== Connector Lifecycle Model
include::docs/connector-lifecycle-model.adoc[]


[[coding_standards_and_best_practices]]
= Coding Standards and Best Practices
include::docs/development-best-practices.adoc[]


[[static-code-analysis-and-coverage]]
= Static Code Analysis and Coverage
include::docs/static-code-analysis-and-coverage.adoc[]


[[functional_tests_automation]]
= Functional Tests Automation
include::docs/functional-tests-automation.adoc[]


[[anypoint-studio-interoperability-testing]]
= Anypoint™ Studio Interoperability Testing
include::docs/anypoint-studio-interoperability-testing.adoc[]


[[cloudhub-interoperability-testing]]
= CloudHub Interoperability Testing
include::docs/cloudhub-interoperability-testing.adoc[]

// [interoperability-test-plugin]
// = Development: Interoperability Testing using DevKit Plugin
// TODO

[[documentation]]
= Documentation & Release Notes
include::docs/documentation.adoc[]


[[appendixes]]
= Appendixes & Templates


== Connector Project Directory Layout

* link:attachments/project-directory-layout.html[Connector Project Directory Layout]



== Common Public Attribution License Version 1.0 (CPAL)

* link:attachments/CPAL.html[Common Public Attribution License Version 1.0 (CPAL)]



== Functional Tests Automation: HowTo

* link:attachments/debugging.html[Debugging]


== Anypoint™ Studio Interoperability Testing: HowTo

* link:attachments/usage-without-anypoint-studio.html[Usage without Anypoint™ Studio]
* link:attachments/plugin-result-files.html[Plugin Result Files]
* link:attachments/project-details.html[Project Details]


== Anypoint™ Connectors Manual Test Suite Template

* https://drive.google.com/uc?export=download&id=0B8N265C555thOGhVd1B6eXFiUDA[Manual Test Suite Template]


[[certification-checklist]]
== Certification Checklists

* https://drive.google.com/uc?export=download&id=0B8N265C555thOG5HZDRTOTEtUXM[Connector Certification Checklist]
* https://drive.google.com/uc?export=download&id=0B8N265C555thNW0tMElvejlVVGc[Manual Interop Test Run Checklist]
