:doctype: book
:compat-mode:
:page-layout!:
:toc: left
:toclevels: 1
:imagesdir: assets
:compat-mode!:
:linkcss:
:source-highlighter: coderay

= Anypoint Connector Certification Process

*version 0.9*



[[intro]]
= Certification

MuleSoft has expanded the Anypoint™ Connector platform enabling partners, from out MuleSoft Partner Program, and third-party development groups, to develop Anypoint connectors.

Every connector in the MuleSoft Anypoint Platform must go through a mandatory *Certification Process* before final release. The certification process has been conceived to assess the overall quality of all available connectors, ensuring that every connector published in the MuleSoft's connectors repository strictly follow industry best practices. As a result of this certification process, we are able to define a high quality threshold for every Mulesoft connector available in the platform.

All available connectors, either built by our partners or by our internal development team, go through the certification process, which is carried out by Mulesoft's internal team. Once a connector passes certification, it is branded as a MuleSoft-certified connector and published in the MuleSoft's connectors repository.


The scope of this process mainly depends on the composition of the connector, where a more complex connector will require further step in the certification process. Our approach is to test every functional block of the connector prior releasing.



This document first introduces the entire *connector lifecycle model*, which includes four different stages: On-board, Development, Certification and Publishing.

. On-board: Takes into consideration the legal engagement between a third-party development group, or partner, and MuleSoft.
. Development: Development phase, considering strictly testing methodologies.
. Certification: The certification process per-se, carried out by a MuleSoft.
. Publishing: Considers the final deployment of the certified connector within MuleSoft's connectors repository. 

Within these stages, we only take into consideration the second and third: Development and Certification. The first stage in out of the scope of this document, while the last one hardly requires interaction from the developer's side and therefore it will be omitted.



//The following list gathers different high-level objectives to be acomplished during the certification of an Anypoint connector.


//. Automated code scan
//. Manual code review and black box testing
//. Manual and automated tests review
//. Repository structure review
//. Documentation review
//. Runtime-compatibility review
//. Static code analysis



include::docs/certification-process-introduction.adoc[]


[[development-best-practices]]
= Development: Coding Standards and Best Practices
---

This section is about best development practices, these are a set of rules that the connector development community has learned over time which can help improve the quality of your connector.

include::docs/development-best-practices.adoc[]

[[documentation]]
= Documentation deliverables
---
include::docs/documentation.adoc[]


[[functional-tests-automation]]
= Development: Functional Tests Automation
---

include::docs/functional-tests-automation.adoc[]

[[static-code-analysis-and-coverage]]
= Development: Static Code Analysis and Coverage
---

include::docs/static-code-analysis-and-coverage.adoc[]

[[anypoint-studio-interoperability-testing]]
= Development: Anypoint Studio Interoperability Testing
---

include::docs/anypoint-studio-interoperability-testing.adoc[]

[[cloudhub-interoperability-testing]]
= Development: CloudHub Interoperability Testing
---

include::docs/cloudhub-interoperability-testing.adoc[]


[[appendixes]]
= Development: Appendixes
---

== Development Appendix A: Anypoint Connectors Documentation Template

* link:attachments/documentationTemplate.html[Documentation Template]

* link:attachments/readme.html[README.md Template]

* link:attachments/project-directory-layout.html[Connector Project Directory Layout]

* link:attachments/CPAL.html[Common Public Attribution License Version 1.0 (CPAL)]

== Development Appendix B: Functional Tests Automation

* link:attachments/debugging.html[Debugging]

== Development Appendix C: Anypoint Studio Interoperability Testing

* link:attachments/usage-without-anypoint-studio.html[Usage without Anypoint Studio]
* link:attachments/plugin-result-files.html[Plugin Result Files]
* link:attachments/project-details.html[Project Details]

== Development Appendix D: Anypoint Connectors Release Notes Template

* link:attachments/releaseNotesTemplate.html[Release Notes Template]

== Development Appendix E: Anypoint Connectors Manual Test Suite Template

* https://drive.google.com/uc?export=download&id=0B8N265C555thOGhVd1B6eXFiUDA[Manual Test Suite Template]

[[certification-checklist]]
== Development Appendix F: Certification Checklists

Download and complete the Connector Certification Checklist and its related Manual Interop Test Run Checklist according to the cases derived from analising your connector based on the Interoperability QA Guidelines.

* https://drive.google.com/uc?export=download&id=0B8N265C555thOG5HZDRTOTEtUXM[Connector Certification Checklist]

* https://drive.google.com/uc?export=download&id=0B8N265C555thNW0tMElvejlVVGc[Manual Interop Test Run Checklist]


