:doctype: book
:compat-mode:
:page-layout!:
:toc: left
:toclevels: 1
:imagesdir: assets
:compat-mode!:
:linkcss:
:source-highlighter: coderay

= Anypoint Connector Certification Process

*version 0.9*

[intro]
= Introduction

MuleSoft has expanded the Anypoint™ Connector offering to enable third-party developers and partners to develop Anypoint Connectors.
All connectors enrolled in the MuleSoft Partner Program must go through a mandatory periodic Certification Process. The Certification Process has been developed to assess the quality of connectors, to ensure that connectors published on the MuleSoft Web page follow industry best practices for development, and to promote trust.
All connectors built by external developers and/or partners go through a Certification Process conducted by MuleSoft’s internal team. Once a connector passes certification, the connector is branded as a MuleSoft-certified connector and published on the MuleSoft web site. 

The scope of the certification process depends on the composition of the connector. Our approach is to test all parts of the connector to ensure that our mutual customers and their platforms are not put at risk.
The items below are a list of the high-level testing performed on each connector during the certification process:

. Automated code scan
. Manual code review and black box testing
. Manual and automated tests review
. Repository structure review
. Documentation review
. Compatibility review
. Static code analysis

In the following sections, each one of the topics to be completed as part of the certification will be described.

include::docs/certification-process-introduction.adoc[]

[devGuidelines]
= Coding Standards and Best Practices

This section is about best development practices, these are a set of rules that the connector development community has learned over time which can help improve the quality of your connector.

include::docs/developement-best-practices.adoc[]

[functionalQAGuidelines]
= Automated Functional Testing

include::docs/functional-qa-guidelines.adoc[]

[functional-test-plugin]
= Studio Functional Test Plugin

include::docs/functional-test-plugin.adoc[]

[interoperability-test-plugin]
= Studio Interoperability Test Plugin

include::docs/studio-interopetability-test-plugin.adoc[]

[sonar]
= Static Code Analysis and Code Coverage

include::docs/sonarqube.adoc[]

[studio-interopetability-QA-guidelines]
= Studio Interoperability QA

include::docs/studio-interopetability-QA-guidelines.adoc[]
include::docs/studio-interopetability-QA-guidelines-2.adoc[]

[templates]
= Templates
== Anypoint Connectors Documentation Template

https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/templates/documentationTemplate.adoc[Documentation Template]

== Anypoint Connectors Release Notes Template

https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/templates/releaseNotesTemplate.adoc[Release Notes Template]

== Anypoint Connectors Manual Test Suite Template

https://docs.google.com/a/mulesoft.com/spreadsheets/d/1xqwGw5msku30sfjx6bpJDP9wZZ15cP2TcEzEq6pM9QM/edit?usp=sharing[Manual Test Suite Template]

== Certification Checklist

Download and complete the document along the process.

https://drive.google.com/file/d/0B8N265C555thOG5HZDRTOTEtUXM/view?usp=sharing
