////
The following is the approved connector user guide template for documenting MuleSoft Supported Connectors.
////

= Connector Name
:keywords: add_keywords_separated_by_commas
:imagesdir: ./_images
:toc: macro
:toclevels: 2


toc::[]

////
URLs should always follow "link:"
////


---

== Introduction

First sentence introduces the connector and describes its basic function.
//Global rule: the word "connector" should be lower case except when appearing in titles, important URL anchor, and after a MuleSoft tradename such as "Anypoint".

Read through this user guide to understand how to set up and configure a basic flow using the connector. Track feature additions, compatibility, limitations and API version updates with each release of the connector using the link:/release-notes/xyz-connector-release-notes[Connector Release Notes]. Review the connector operations and see how they work by reviewing the link:/link-to-github.io-or-internal-section[Connector Technical Reference] alongside the link:https://www.mulesoft.com/exchange#!/?filters=Salesforce&sortBy=rank[demo applications].

MuleSoft maintains this connector under the link:/mule-user-guide/v/3.7/anypoint-connectors#connector-categories[_Insert Category_] support policy.


=== Prerequisites

This document assumes that you are familiar with … +
To use this connector, … +

=== Requirements

Hardware, software, and technical requirements.

=== Dependencies

What MuleSoft software is required to get this connector to work? +

*Versions* +

What versions of JAR files and MS software is required  ?. What is the version sandbox version during the testing ? +

*Consumers* +
What software is required to user this connector?

=== Namespace

[source, xml]
----

----

=== Schema Location

[source, code, linenums]
----
xsi:schemaLocation="
...

----

For example:

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"

  
      <!-- Insert your configuration elements and your flow here -->
</mule>
----


=== Compatibility
What system versions is supported ?. Patches/APIs versions

---

== Installing and Configuring

=== Installing

How do you install this connector?

=== Configuring

What do you set on configuration? +

=== Updating From an Older Version

What needs to be configured when updating from a previous version of this connector?  +
Are there configuration items for previous MuleSoft software for this connector?

---

== Using This Connector

Outbound, inbound, streaming outbound  +

=== Use Cases and Demos
List use cases for this connector, including a demo for every use case. +


=== Best Practices
To take full advantage of the functionality … +

=== Tips
* <Information from Support>

=== Integration Patterns

___ recognizes these integration patterns for connecting with other systems…

=== Adding to a Flow

Use a ____ Connector in your application -> flowchart +

=== Query Types

If talking to a database, what queries are allowed by this connector? +

=== Increasing Performance

What can you set in the connector to increase performance?

---

== Example Use Case

Explain what this example is for.

It should contain a fully functional Mule application as a demo, where the use case is considered. The demo needs to be simple and only considering a single use case.

===  Anypoint Studio Visual Editor | XML Editor

Explain how to create this case with  Anypoint Studio  visual editor and XML editor +

[tabs]
-----
[tab,title="Studio Visual Editor"]
....
[tab content goes here]
....
[tab,title="XML Editor"]
....
[tab content goes here]
....
-----

=== Code Example

Number code example lines and explain blocks of lines

---
=== F.A.Q

* Add here all the items you consider useful.

=== See Also

* Access the link:/release-notes/<System_Name>-connector-release-notes[<System_Name> Connector Release Notes].
