== Code Conventions

This sections covers the following areas:

. Standard Java coding conventions.
. Devkit and connector coding conventions.
. Static code analysis review is enforced by http://www.methodsandtools.com/tools/tools.php?sonar[Sonar]. To install a local instance, see __Anypoint Connectors Static Code Analysis__.

__Note__: Do not use Mule internal APIs for coding connectors.

== Directory Structure
Your connector project directory structure must follow the conventions described in __Appendix C__. If you create your connector project using the DevKit Studio Plugin, the structure generates by default.

== Maven Conventions and Setup

The following section describes set of convenitions and best practices to follow at the time to define your connector Maven project structure.

== Best Practices

These are mandatory practices to be honored:

* Do not overwrite org.mule.tools.devkit:mule-devkit-parent properties.
* Do not reference SNAPSHOT dependencies either in plugins or dependencies.

// == Multimodule Layout
// @Todo: Alejandro: could you please complete this section ?

=== Project Structure Validation

The following plugin must be configure as part of the connectors pom.xml. I will be responsible for validating the project structure.
Copy and paste the following snippets in your connector pom.xml:

[source,xml]
----
<build>
    ...
    <plugins>
        ...
       <plugin>
            <groupId>org.mule.certification</groupId>
            <artifactId>project-structure-validation</artifactId>
            <version>1.0.4</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>y</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
    ...
</build>
----

== DataMapper Compliance
To have the best experience in Anypoint Studio, connectors must be DataMapper compliant. To achieve this, all operations must follow these recommendations.

Any argument, returned or received, must be one of the following data types:
. Map
. POJO
. List<Map>
. List<String>
. List<POJO>
. List<List<String>>

These types must be part of the method signature so that DataMapper can auto-recognize the types in it's mapping UI.

__Important__: Only use a map if you cannot use a POJO. 
Only use a map if your data:
. Is schemaless, for example if created using MongoDB.
. Has user customizable schemas, if created with Salesforce.
. Has unknown content.


|===
|Good Example| Bad Example

|List<Map> query()| List<DBObject> query
|void send(Invoice invoice)| void send(Object object)
|Invoice getInvoice(String id)| Object get(String id, Class typeToCreate)

All operations must have a single object to take input from DataMapper. The object must be a single object, not multiple arguments. This object is called the Primary argument.
|===
|===
|Good Example| Bad Example

|void createInvoice(Invoice invoice)| createInvoice(Header header, List<LineItems> lineItems)
|void upsert(List<Map> sobjects, String type, String externalFieldId)| N/A - Multiple arguments are still needed!
|GetTaxResult getTax(TaxRequest request)| 
```public GetTaxResult getTax(String companyCode, +
    AvalaraDocumentType docType, +
    @Optional String docCode, +
    Date docDate, +
    @Optional String salespersonCode, +
    String customerCode, +
    @Optional String customerUsageType, +
    String discount, +
    @Optional String purchaseOrderNo) +
```
|===

=== Annotations
If you have multiple arguments, annotate the Primary argument with:

`@Default("#[payload]")`

This way DataMapper knows which argument in the operation to use for mapping.

== Connector Demo Example
A Mule application's endpoints allow a user to interact with the service and API using the connector. Endpoints are committed to the GitHub repository along with source code. Use services or API use cases to determine which connector operations to select.

Creation criteria:
. Ensure that an app can be run by entering credentials without additional configuration or connector installation.
. Use placeholders for credentials.
. Ensure that flow names and message processors display names that make the use case easy to understand.
. Provide instructions on how to run the app in the README.md file of the GitHub demo (example https://github.com/mulesoft/sqs-connector/tree/master/demo[SQS]).
. Expose a set of endpoints that the user can access following the steps in the README.md to reproduce a use case. An example is the https://github.com/mulesoft/sqs-connector/tree/master/demo[SQS] demo.
. Consider implementing a CRUD (or similar) use case with chained processors whose payloads get logged into the Studio console (for example, https://github.com/mulesoft/s3-connector/tree/master/demo/s3connectorstudiodemo[S3]). 
. Use DataMapper for Standard or Premium connectors' CRUD (or a similar) use case if API methods attributes and/or return types allow it. 
. Consider basic error handling in the Mule app.

== Documentation

MuleSoft generates a Javadoc technical reference by DevKit through Javadoc, based on the comments inside your code. Provide release notes as part of the documentation following the guidelines mentioned in CHANGELOG.md (see Appendix B).


== Appendix 
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixA.adoc[Appendix A]
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixB.adoc[Appendix B]
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixC.adoc[Appendix C]
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixD.adoc[Appendix D]

