== Functional Automation Tests
Use http://www.mulesoft.org/documentation/display/current/Developing+DevKit+Connector+Tests[Developing DevKit Connector Tests] to build a test suite using the style of the https://docs.google.com/a/mulesoft.com/spreadsheet/ccc?key=0AvgooFprI9W5dGM2WXZpaTU4bWtRdFVLUGdkcnNIVEE&usp=drive_web#gid=21[Connector interoperability test suite template]. Prior to entering the certification phase, all test cases in this test suite must run and achieve "Passed" status.

. Interoperability testing for a connector covers the following scenarios (if applicable):
.. Anypoint Studio interoperability 
... Installation
... Connectivity
... Metadata
... XML Generation
... Datamapper compliance
.. CloudHub interoperability

. Use the https://github.com/mulesoft/mule-connector-test[Mule Connector Test Framework] for information on how to call Mule flows and process the corresponding results. Also use the https://github.com/mulesoft/mule-connector-test/wiki/Connectors-automation[Connectors Automation] guide to create and run tests. A functional test suite must be part of your connector. You must also provide an Apache Maven Surefire report as a deliverable to the certification phase. All functional tests must be in "Passed" status.

== Code Conventions

This sections covers the following areas:

. Standard Java coding conventions.
. Devkit and connector coding conventions.
. Static code analysis review is enforced by http://www.methodsandtools.com/tools/tools.php?sonar[Sonar]. To install a local instance, see __Anypoint Connectors Static Code Analysis__.

__Note__: Do not use Mule internal APIs for coding connectors.

== Directory Structure
Your connector project directory structure must follow the conventions described in __Appendix C__. If you create your connector project using the DevKit Studio Plugin, the structure generates by default.

== Project Structure Check Tool
After you install the Studio Plugin, run the Project Structure Check plugin to validate that the structure of your project is correct.

To run the plugin, add this execution to your connector’s pom.xml file: 

[source,xml]
----
<build>
    ...
    <plugins>
        ...
       <plugin>
            <groupId>org.mule.certification</groupId>
            <artifactId>project-structure-validation</artifactId>
            <version>1.0.4</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>y</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
    ...
</build>
----

== DataMapper Compliance
To have the best experience in Anypoint Studio, connectors must be DataMapper compliant. To achieve this, all operations must follow these recommendations.

Any argument, returned or received, must be one of the following data types:
. Map
. POJO
. List<Map>
. List<String>
. List<POJO>
. List<List<String>>

These types must be part of the method signature so that DataMapper can auto-recognize the types in it's mapping UI.

__Important__: Only use a map if you cannot use a POJO. 
Only use a map if your data:
. Is schemaless, for example if created using MongoDB.
. Has user customizable schemas, if created with Salesforce.
. Has unknown content.


|===
|Good Example| Bad Example

|List<Map> query()| List<DBObject> query
|void send(Invoice invoice)| void send(Object object)
|Invoice getInvoice(String id)| Object get(String id, Class typeToCreate)

All operations must have a single object to take input from DataMapper. The object must be a single object, not multiple arguments. This object is called the Primary argument.
|===
|===
|Good Example| Bad Example

|void createInvoice(Invoice invoice)| createInvoice(Header header, List<LineItems> lineItems)
|void upsert(List<Map> sobjects, String type, String externalFieldId)| N/A - Multiple arguments are still needed!
|GetTaxResult getTax(TaxRequest request)| 
```public GetTaxResult getTax(String companyCode, +
    AvalaraDocumentType docType, +
    @Optional String docCode, +
    Date docDate, +
    @Optional String salespersonCode, +
    String customerCode, +
    @Optional String customerUsageType, +
    String discount, +
    @Optional String purchaseOrderNo) +
```
|===

=== Annotations
If you have multiple arguments, annotate the Primary argument with:
```
@Default("#[payload]")
```
This way DataMapper knows which argument in the operation to use for mapping.

== Connector Demo or Templates
A Mule application's endpoints allow a user to interact with the service and API using the connector. Endpoints are committed to the GitHub repository along with source code. Use services or API use cases to determine which connector operations to select.

Creation criteria:
. Ensure that an app can be run by entering credentials without additional configuration or connector installation.
. Use placeholders for credentials.
. Ensure that flow names and message processors display names that make the use case easy to understand.
. Provide instructions on how to run the app in the README.md file of the GitHub demo (example https://github.com/mulesoft/sqs-connector/tree/master/demo[SQS]).
. Expose a set of endpoints that the user can access following the steps in the README.md to reproduce a use case. An example is the https://github.com/mulesoft/sqs-connector/tree/master/demo[SQS] demo.
. Consider implementing a CRUD (or similar) use case with chained processors whose payloads get logged into the Studio console (for example, https://github.com/mulesoft/s3-connector/tree/master/demo/s3connectorstudiodemo[S3]). 
. Use DataMapper for Standard or Premium connectors' CRUD (or a similar) use case if API methods attributes and/or return types allow it. 
. Consider basic error handling in the Mule app.

== Documentation
Ensure that a connector’s documentation is legible and follows this template.

MuleSoft generates a Javadoc technical reference by DevKit through Javadoc, based on the comments inside your code.

Provide release notes as part of the documentation following the guidelines mentioned in CHANGELOG.md (see Appendix B).

== Licensing
If your connector is open source 

== Appendix A
=== README.md Template

----
# [Name] Anypoint Connector
# ---------------------------------------------------
[Connector description including destination service or application]

### Author
Example:
MuleSoft Inc.

### Supported Mule runtime versions
Examples:
Mule 3.4.x, 3.5.x
Mule 3.4.1

### [Destination service or application name] supported versions
Example:
Oracle E-Business Suite 12.1 and above.

### Service or application supported modules
Example:
Oracle CRM
Oracle Financials
or 
Salesforce API v.24
Salesforce Metadata API

### Installation 

You can access the full documentation <here>.

### Reporting Issues
----

(Only for open source connectors)
We use GitHub:Issues for tracking issues with this connector. You can report new issues at this link https://github.com/mulesoft/<connector-repository-name>/issues.

== Appendix B
=== CHANGELOG.md Template
```
# [Connector name] Release Notes
# --------------------------------------------------------------------
### Date: <DD-MMM-YYYY>
Example: 24-Jan-2014

### Version: 
<connector version> (default value: 0.1)

### Supported API versions: 
Example: Salesforce Bulk API v.28, SOAP API V.28 (include links to API docs)

### Supported Mule Runtime Versions: 
Example: 3.4.x, 3.5.0

### New Features and Functionality
(default value: Initial version) 
Example: Added support for Query. https://github.com/mulesoft/salesforce-connector/issues/61

### Closed Issues in this release 
(include issue link when possible)
Example: Fixed problem with lost telefone on Bulk Update (CLDCONNECT-123).

### Known Issues in this release
Example: Session ID expires after 30 days. https://github.com/mulesoft/salesforce-connector/issues/62
```

== Appendix C
=== Connector Project Directory Layout 
. */demo*: Contains demo Mule application covering use cases functionality. 
. */doc*: Contains documentation for the connector, such as descriptions of the service’s specific API calls or similar. The main file should be called 
The documentation should be written using markdown follow the Documentation Template and it should be called user_manual.md.
VIDEO_TRANSCRIPT.md (optional)
Contains video tutorial transcription. The video tutorial highlights the connector functionality in a real use case scenario and is uploaded to MuleSoft‘s YouTube account

. */icons*: Contains icons for the connector using 24x16, 18x32, or 300x300 pixels. 

. */src*: Contains the source code for the connector including tests cases source code and results.

. *LICENSE_HEADER.txt*: 
.. For closed source connectors - Mulesoft :
(c) 2003-2014 MuleSoft, Inc. This software is protected under international copyright law. All use of this software is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between you and MuleSoft. If such an agreement is not in place, you may not use the software.

.. For open source connectors:
(c) 2003-2014 MuleSoft, Inc. The software in this package is published under the terms of the CPAL v1.0 license, a copy of which has been included with this distribution in the LICENSE.md file.

. *LICENSE.md*: 
.. For closed source connectors:
(c) 2003-2014 MuleSoft, Inc. This software is protected under international copyright law. All use of this software is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between you and MuleSoft. If such an agreement is not in place, you may not use the software.
.. For open source connectors:
Please copy CPAL 1.0 from Appendix D

. *CHANGELOG.md*: Change log file containing the changes introduced in each released version of the connector. See below for details

. *README.md*: Readme file for the connector. See below for details.

. *pom.xml*: Ensure you are referencing mule-devkit-parent in your pom.xml.

[source,xml]
----
<parent>
    <groupId>org.mule.tools.devkit</groupId>
    <artifactId>mule-devkit-parent</artifactId>
    <version>{devkit.version}</version>
</parent>
----

== Appendix D

https://docs.google.com/document/d/1A3X8tSxtqyc9ifWdJeiktBYJHmvQyOPzuIcCVYkQkXg/edit?usp=sharing[Common Public Attribution License Version 1.0 (CPAL)]
