== Code Conventions

This sections covers the following areas:

Standard Java Coding Conventions
. DevKit Standards and Best Practices
. Maven Conventions and Setup
. Connector Demo Example

It's important to point out that in the following steps of the certification most of this practices will be validated using automated tools such as SonarQue.

== Standard Java Coding Conventions

=== Static Analysis Rules

We have defined as set of static inspections rules that are enforced by SonarQube. This rules are aimed to detect potential bugs and bad coding practices.
More details about this could be found in the section http://mulesoft.github.io/connector-certification-docs/current/user-manual.html#_static_code_analysis_with_sonarqube[Static Code Analysis & Code Coverage]

== Maven Conventions and Setup

The following section describes set of conventions and best practices to follow at the time to define your connector Maven project structure.

=== Best Practices

These are mandatory practices to be honored:

* Follow Maven default name conventions http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
* Do not overwrite org.mule.tools.devkit:mule-devkit-parent properties.
* Do not reference SNAPSHOT dependencies either in plugins or dependencies.

// == Multimodule Layout
// @Todo: Alejandro: could you please complete this section ?

=== Connector Structure

If you create your connector project using the DevKit Studio Plugin, the structure generates by default is the recommended approach.
If you are interested in more details, the project directory structure are described in the __Appendix C__.

In order to provide automatic enforcement of this rules, the following plugin must be configure as part of the connectors pom.xml. I will be responsible for validating the project structure.
Copy and paste the following snippets in your connector pom.xml:

[source,xml]
----
<build>
    ...
    <plugins>
        ...
       <plugin>
            <groupId>org.mule.certification</groupId>
            <artifactId>project-structure-validation</artifactId>
            <version>1.0.4</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>y</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
    ...
</build>
----

== DevKit Standards and Best Practices
=== DataMapper Compliance

To have the best experience in Anypoint Studio, connectors must be DataMapper compliant. To achieve this, all operations must follow these recommendations.

Any argument, returned or received, must be one of the following data types:
. Map
. POJO
. List<Map>
. List<String>
. List<POJO>
. List<List<String>>

These types must be part of the method signature so that DataMapper can auto-recognize the types in it's mapping UI.

__Important__: Only use a map if you cannot use a POJO. 
Only use a map if your data:
. Is schemaless, for example if created using MongoDB.
. Has user customizable schemas, if created with Salesforce.
. Has unknown content.


|===
|Good Example| Bad Example

|List<Map> query()| List<DBObject> query
|void send(Invoice invoice)| void send(Object object)
|Invoice getInvoice(String id)| Object get(String id, Class typeToCreate)

All operations must have a single object to take input from DataMapper. The object must be a single object, not multiple arguments. This object is called the Primary argument.
|===
|===
|Good Example| Bad Example

|void createInvoice(Invoice invoice)| createInvoice(Header header, List<LineItems> lineItems)
|void upsert(List<Map> sobjects, String type, String externalFieldId)| N/A - Multiple arguments are still needed!
|GetTaxResult getTax(TaxRequest request)| 
```public GetTaxResult getTax(String companyCode, +
    AvalaraDocumentType docType, +
    @Optional String docCode, +
    Date docDate, +
    @Optional String salespersonCode, +
    String customerCode, +
    @Optional String customerUsageType, +
    String discount, +
    @Optional String purchaseOrderNo) +
```
|===

=== Annotations
If you have multiple arguments, annotate the Primary argument with:

`@Default("#[payload]")`

This way DataMapper knows which argument in the operation to use for mapping.

=== DevKit Generated API Doc

Connector documentation is composed of two different type of documentation: DevKit Generated DevKit API Doc and the Connector Documentation.

DevKit API Doc is automatically generated by DevKit based on the JavaDoc documentation at the connector class. This is one of the most important information used by the developer at the time of of using the connector.

// @Todo: Hernan - Que sugeris ?. LDAP. We need to explain how to check the generated documentation.
// Recomendation with Samples


== Connector Demo Example

// @Todo: Paulo - Here we need to complete with Justin's input feedback.

A Mule application's endpoints allow a user to interact with the service and API using the connector. Endpoints are committed to the GitHub repository along with source code. Use services or API use cases to determine which connector operations to select.

Creation criteria:
. Ensure that an app can be run by entering credentials without additional configuration or connector installation.
. Use placeholders for credentials.
. Ensure that flow names and message processors display names that make the use case easy to understand.
. Provide instructions on how to run the app in the README.md file of the GitHub demo (example https://github.com/mulesoft/sqs-connector/tree/master/demo[SQS]).
. Expose a set of endpoints that the user can access following the steps in the README.md to reproduce a use case. An example is the https://github.com/mulesoft/sqs-connector/tree/master/demo[SQS] demo.
. Consider implementing a CRUD (or similar) use case with chained processors whose payloads get logged into the Studio console (for example, https://github.com/mulesoft/s3-connector/tree/master/demo/s3connectorstudiodemo[S3]).
. Use DataMapper for Standard or Premium connectors' CRUD (or a similar) use case if API methods attributes and/or return types allow it.
. Consider basic error handling in the Mule app.

== Appendix
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixA.adoc[Appendix A]
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixB.adoc[Appendix B]
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixC.adoc[Appendix C]
. https://github.com/mulesoft/connector-certification-docs/blob/docs/current/attachments/development/appendixD.adoc[Appendix D]

