Documentation is a vital part of the development stage, where the development team must follow strictly documentation standars.


== Built-in documentation

Part of the documentation must be packed within the connector source code. A _doc_ folder needs to be created directly in the root of the connector project, where the following documents need to be placed.

. User Guide
. Release Notes
. ReadMe

In addition, an extra folder named _images_ need to be created directly inside the _doc_ folder. This resource folder will contain any resource (images, XMLs, etc.) used in the documentation.



=== User Guide

The user guide needs to be fully descriptive and easy to read, including not only technical documentation but use cases and error solutions. The documentation should be written using asciidoc syntax and the resulting file called user_manual.adoc. A template can be found https://drive.google.com/uc?export=download&id=0B-1b74eXfPFHckxzdzJNWmlHVUk[here].



=== Release Notes

Release notes need to be highly descriptive, specially including backward compatibility of the released connector with previous versions. A template can be found https://drive.google.com/uc?export=download&id=0B-1b74eXfPFHYXNtM1ZIRXdVOTQ[here].

=== ReadMe

A README.md template can be found https://drive.google.com/uc?export=download&id=0B-1b74eXfPFHcHhWMUEwUFBzWE0[here].


== Connector Apidocs

Each public connector require that:

. The description provides a clear and a complete explanation of its purpose.
. The XML sample is up-to-date with the method signature and can be directly pasted in Anypoint™ Studio.
. The attributes that affect methods behaviour are documented in detail.

For further information, please refer to:
	
http://mulesoft.github.io/salesforce-connector/mule/sfdc-config.html#convert-lead[Salesforce Connector: convert-lead Apidocs].

http://mulesoft.github.io/salesforce-connector/mule/sfdc-config.html#create[Salesforce Connector: create Apidocs].