Documentation is a vital part of the development stage, where the development team must follow strictly documentation standars.


== Connector built-in documentation

Part of the documentation must be packed within the connector source code. A _doc_ folder needs to be created directly in the root of the connector project, where the following documents need to be placed.

. User Guide
. Release Notes
. ReadMe

In addition, an extra folder named _resources_ need to be created directly inside the _doc_ folder. This resource folder will contain any resource (images, XMLs, etc.) used in the documentation.



=== User Guide

The user guide needs to be fully descriptive and easy to read, including not only technical documentation but use cases and error solutions. A template can be found link:attachments/documentationTemplate.html[here.



=== Release Notes

Release notes need to be highly descriptive, specially including backward compatibility of the released connector with previous versions. A template can be found link:attachments/releaseNotesTemplate.html[here].

=== ReadMe

A README.md template can be found link:attachments/readme.html[here].




ver la parte de project layout



== Connector Apidocs

Each public connector require that:

. The description provides a clear and a complete explanation of its purpose.
. The XML sample is up-to-date with the method signature and can be directly pasted in Anypoint™ Studio.
. The attributes that affect methods behaviour are documented in detail.

For further information, please refer to:
	
http://mulesoft.github.io/salesforce-connector/mule/sfdc-config.html#convert-lead[Salesforce Connector: convert-lead Apidocs].
http://mulesoft.github.io/salesforce-connector/mule/sfdc-config.html#create[Salesforce Connector: create Apidocs].