////
The following is the approved connector user guide template for documenting MuleSoft Supported Connectors.
////

= Connector Name
:keywords: add_keywords_separated_by_commas
:imagesdir: ./_images
:toc: macro
:toclevels: 2
////
Image names follow "image:". Identify images using the connector name, preferably without the word "connector"
URLs should always follow "link:"
////

// Dropdown for Connector Version
//  Children: Technical Reference / Demos

toc::[]


== Introduction

First sentence introduces the connector and describes its basic function.
//Global rule: the word "connector" should be lower case except when appearing in titles, important URL anchors, and after a MuleSoft tradename such as "Anypoint".

Read through this user guide to understand how to set up and configure a basic flow using the connector. Track feature additions, compatibility, limitations and API version updates with each release of the connector using the link:/release-notes/xyz-connector-release-notes[Connector Release Notes]. Review the connector operations and functionality using the link:/link-to-github.io-or-internal-section[ Technical Reference] alongside the link:https://www.mulesoft.com/exchange#!/?filters=Salesforce&sortBy=rank[demo applications].

MuleSoft maintains this connector under the link:/mule-user-guide/v/3.8/anypoint-connectors#connector-categories[_Insert Category_] support policy.


== Prerequisites

This document assumes that you are familiar with Mule,
////
examples:
////
link:/mule-user-guide/v/3.8/anypoint-connectors[Anypoint Connectors], and
link:/mule-fundamentals/v/3.8/anypoint-studio-essentials[Anypoint Studio Essentials]. To increase your familiarity with Studio, consider completing a link:/mule-fundamentals/v/3.8/basic-studio-tutorial[Anypoint Studio Tutorial]. This page requires some basic knowledge of link:/mule-fundamentals/v/3.8/mule-concepts[Mule Concepts], link:/mule-fundamentals/v/3.8/elements-in-a-mule-flow[Elements in a Mule Flow], and link:/mule-fundamentals/v/3.8/global-elements[Global Elements].


=== Compatibility

What system versions is supported ?. Patches/APIs versions
////
optional
////
What MuleSoft software is required to get this connector to work? +

*Versions* +

What versions of JAR files and MS software is required  ?. What is the version sandbox version during the testing ? +

*Consumers* +
What software is required to user this connector?

=== Connector Namespace and Schema

When designing your application in Studio, the act of dragging the connector from the palette onto the Anypoint Studio canvas should automatically populate the XML code with the connector *namespace* and *schema location*.

[TIP]
If you are manually coding the Mule application in Studio's XML editor or other text editor, paste these into the header of your *Configuration XML*, inside the `<mule>` tag.

[source, xml,linenums]
----
<mule xmlns:connector="http://www.mulesoft.org/schema/mule/connector"
  ...
  xsi:schemaLocation="http://www.mulesoft.org/schema/mule/connector http://www.mulesoft.org/schema/mule/connector/current/mule-connector.xsd">
  ...
  <flow name="yourFlow">
  ...
  </flow>
</mule>
----

== Install the Connector

You can install the connector in Anypoint Studio using the instructions in
link:/mule-fundamentals/v/3.8/anypoint-exchange#installing-a-connector-from-anypoint-exchange[Installing a Connector from Anypoint Exchange].

=== Upgrading from an Older Version

If you’re currently using an older version of the connector, a small popup appears in the bottom right corner of Anypoint Studio with an "Updates Available" message.

. Click the popup and check for available updates. 
. Click the Connector version checkbox and click *Next* and follow the instructions provided by the user interface. 
. *Restart* Studio when prompted. 
. After restarting, when creating a flow and using the Object Store Connector, if you have several versions of the connector installed, you may be asked which version you would like to use. Choose the version you would like to use.

Additionally, we recommend that you keep Studio up to date with its latest version.

== Configure the Connector Global Element

What do you set on configuration? +

== Using the Connector

Outbound, inbound, streaming outbound  +

[NOTE]
See the full list of operations for the latest version of the connector link:http://mulesoft.github.io/sns-connector/3.0.0/apidocs/mule/sns-config.html[here].


=== Using the Connector in a Mavenized Mule App

If you are coding a Mavenized Mule application, this XML snippet must be included in your `pom.xml` file.

[source,xml,linenums]
----
<dependency>
  <groupId></groupId>
  <artifactId></artifactId>
  <version></version>
</dependency>
----

[TIP]
Inside the `<version>` tags, put the desired version number, the word `RELEASE` for the latest release, or `SNAPSHOT` for the latest available version.


== Connector Performance

To define the pooling profile for the connector manually, access the *Pooling Profile* tab in the applicable global element for the connector.

For background information on pooling, see link:/mule-user-guide/v/3.8/tuning-performance[Tuning Performance].


=== Integration Patterns
////
optional
////

___ recognizes these integration patterns for connecting with other systems…

=== Best Practices
////
optional
////
To take full advantage of the functionality … +

=== Tips
////
optional
////
* <Information from Support>


== Demo Mule Applications Using Connector
////
add links to demos
////


=== Example Use Case
// Limit to 10 steps
// Do NOT provide a parallel XML walkthrough. Weave any XML details into steps. Also avoid any unnecessary or marginally helpful screenshots

List potential use cases for this connector. Explain what this example is for

The section should contain a fully functional Mule application as a demo, where the use case is considered. Explain how to create this case with Anypoint Studio Visual editor and what the XML looks like, using a numbered list.

////
optional
[tabs]
-----
[tab,title="Studio Visual Editor"]
....
[tab content goes here]
....
[tab,title="XML Editor"]
....
[tab content goes here]
....
-----
////

=== Example Use Case - XML

Paste this into Anypoint Studio to interact with the example use case application discussed in this guide.

[source,xml,linenums]
----

----

=== See Also

* Access the link:/release-notes/<System_Name>-connector-release-notes[<System_Name> Connector Release Notes].
