#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print "commit-msg: On branch '%s'." % branch

# Check they're not committing to develop directly
if branch == 'develop':
    print "commit-msg: Hey... you're not supposed to commit to develop directly. Please create a branch and then submit a Pull Request."
    sys.exit(1)

# Check they're not committing to master directly
if branch == 'master':
    print "commit-msg: Seriously? You don't commit to master! Oh, BTW... Mariano Goldman has just been informed of this incident :p."
    sys.exit(1)

# Check the commit message if we're on an issue branch
with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    print "File content: '%s'" % content
    result = re.match('^([A-Z]*\-[0-9]*)\s\|\s(.*)$', content, re.MULTILINE)
    if not result:
        print "commit-msg: ERROR! The commit message must include a JIRA issue number like: 'PRJ-XX | The message'."
        sys.exit(1)
