
== Appendix C
=== Connector Project Directory Layout 
. */demo*: Contains demo Mule application covering use cases functionality. 
. */doc*: Contains documentation for the connector, such as descriptions of the service’s specific API calls or similar. The main file should be called 
The documentation should be written using markdown follow the Documentation Template and it should be called user_manual.md.
VIDEO_TRANSCRIPT.md (optional)
Contains video tutorial transcription. The video tutorial highlights the connector functionality in a real use case scenario and is uploaded to MuleSoft‘s YouTube account

. */icons*: Contains icons for the connector using 24x16, 18x32, or 300x300 pixels. 

. */src*: Contains the source code for the connector including tests cases source code and results.

. *LICENSE_HEADER.txt*: 
.. For closed source connectors - Mulesoft :
(c) 2003-2014 MuleSoft, Inc. This software is protected under international copyright law. All use of this software is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between you and MuleSoft. If such an agreement is not in place, you may not use the software.

.. For open source connectors:
(c) 2003-2014 MuleSoft, Inc. The software in this package is published under the terms of the CPAL v1.0 license, a copy of which has been included with this distribution in the LICENSE.md file.

. *LICENSE.md*: 
.. For closed source connectors:
(c) 2003-2014 MuleSoft, Inc. This software is protected under international copyright law. All use of this software is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between you and MuleSoft. If such an agreement is not in place, you may not use the software.
.. For open source connectors:
Please copy CPAL 1.0 from Appendix D

. *CHANGELOG.md*: Change log file containing the changes introduced in each released version of the connector. See below for details

. *README.md*: Readme file for the connector. See below for details.

. *pom.xml*: Ensure you are referencing mule-devkit-parent in your pom.xml.

[source,xml]
----
<parent>
    <groupId>org.mule.tools.devkit</groupId>
    <artifactId>mule-devkit-parent</artifactId>
    <version>{devkit.version}</version>
</parent>
----