////
The following is the approved connector user guide template for documenting MuleSoft Supported Connectors.
////

= Connector Name
:keywords: add_keywords_separated_by_commas
:imagesdir: ./_images
:toc: macro
:toclevels: 2
////
Image names follow "image:". Identify images using the connector name, preferably without the word "connector"
URLs should always follow "link:"
////

toc::[]


== Introduction

First sentence introduces the connector and describes its basic function.
//Global rule: the word "connector" should be lower case except when appearing in titles, important URL anchors, and after a MuleSoft tradename such as "Anypoint".

Read through this user guide to understand how to set up and configure a basic flow using the connector. Track feature additions, compatibility, limitations and API version updates with each release of the connector using the link:/release-notes/xyz-connector-release-notes[Connector Release Notes]. Review the connector operations and functionality using the link:/link-to-github.io-or-internal-section[ Technical Reference] alongside the link:https://www.mulesoft.com/exchange#!/?filters=Salesforce&sortBy=rank[demo applications].

MuleSoft maintains this connector under the link:/mule-user-guide/v/3.7/anypoint-connectors#connector-categories[_Insert Category_] support policy.


== Prerequisites

This document assumes that you are familiar with Mule,
////
examples:
////
link:/mule-user-guide/v/3.7/anypoint-connectors[Anypoint Connectors], and
link:/mule-fundamentals/v/3.7/anypoint-studio-essentials[Anypoint Studio Essentials]. To increase your familiarity with Studio, consider completing one or more link:/mule-fundamentals/v/3.7/basic-studio-tutorial[Basic Studio Tutorial]. This page assumes you understand link:/mule-fundamentals/v/3.7/mule-concepts[Mule Concepts], link:/mule-fundamentals/v/3.7/elements-in-a-mule-flow[Elements in a Mule Flow], and link:/mule-fundamentals/v/3.7/global-elements[Global Elements].

== Requirements

For hardware and software requirements, please visit link:/mule-user-guide/v/3.7/hardware-and-software-requirements[Mule Hardware and Software Requirements] page.

=== Dependencies
////
optional
////
What MuleSoft software is required to get this connector to work? +

*Versions* +

What versions of JAR files and MS software is required  ?. What is the version sandbox version during the testing ? +

*Consumers* +
What software is required to user this connector?

=== Namespace and Schema

[TIP]
When designing your application in Studio, the act of dragging the connector from the palette onto the Anypoint Studio canvas should populate the XML code with the connector *namespace* and *schema location* to be included in your application.

However, if you are coding the Mule application in Studio's XML editor or other text editor, paste these into the header of your *Configuration XML* in the locations specified below.

==== Namespace

[source, xml]
----

----

==== Schema Location

[source, code, linenums]
----
xsi:schemaLocation="
...

----

For example:

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"

  
      <!-- Insert your configuration elements and your flow here -->
</mule>
----


=== Compatibility
What system versions is supported ?. Patches/APIs versions

---

== Installing and Configuring

=== Installing

How do you install this connector?

=== Configuring

What do you set on configuration? +

=== Updating From an Older Version

What needs to be configured when updating from a previous version of this connector?  +
Are there configuration items for previous MuleSoft software for this connector?

---

== Using This Connector

Outbound, inbound, streaming outbound  +

== Example Use Case

List potential use cases for this connector. Explain what this example is for.

The section should contain a fully functional Mule application as a demo, where the use case is considered. Explain how to create this case with Anypoint Studio Visual editor and what the XML looks like, using a numbered list.

////
optional
[tabs]
-----
[tab,title="Studio Visual Editor"]
....
[tab content goes here]
....
[tab,title="XML Editor"]
....
[tab content goes here]
....
-----
////

=== Example Use Case Code

Paste this into Anypoint Studio to interact with the example use case application discussed in this guide.

[source,xml,linenums]
----

----

=== Demos
////
optional
////

=== Best Practices
////
optional
////
To take full advantage of the functionality … +

=== Tips
////
optional
////
* <Information from Support>

=== Integration Patterns
////
optional
////

___ recognizes these integration patterns for connecting with other systems…

=== Adding to a Flow
////
optional
////
Use a ____ Connector in your application -> flowchart +

=== Query Types
////
optional
////
If talking to a database, what queries are allowed by this connector? +

=== Increasing Performance
////
optional
////
What can you set in the connector to increase performance?

---


---
=== F.A.Q
////
optional
////

* Add here all the items you consider useful.

=== See Also

* Access the link:/release-notes/<System_Name>-connector-release-notes[<System_Name> Connector Release Notes].
